[package]
name = "image-view"
version = "0.5.0"
edition = "2021"

[dependencies]
image = "0.24"
terminal_size = "^0.3"
colored = "^2.0"
crossterm = "0.27"
arboard = "3.4"
base64 = "0.22"

[[bin]]
name = "image-view"
path = "./src/main.rs"
